name: bijouknits
favicon: null
layout_spectrum: 1
typography_spectrum: 0.77122
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090b08'
    - '#4f5390'
    - '#fefefa'
    - '#807d88'
    - '#cfc492'
  brandStrength: 0.8125
  lightness: 0.5780860087834299
  saturation: 0.8125
  rhythmicContrast: 0.38440925837494433
purpose: []
