name: bijouknits
favicon: null
layout_spectrum: 0.9995981059037149
typography_spectrum: 0.6292435582727194
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5072477082721889
  lightness: 0.5780860087834299
  saturation: 0.9079532106406987
  rhythmicContrast: 0.38440925837494433
purpose: []
